---
title: "Case Study Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, message=F, warning=F, echo=F}
require(rstan)
require(tidyverse)
require(rstanarm)
require(magrittr)
library(corrplot)
library(caret)
```

```{r load-data, message = FALSE}
data_train<-read_csv("data/data-train.csv")
data_test<-read_csv("data/data-test.csv")
```

```{r}
set.seed(2000)
```

## Introduction


## Methodology

After loading the data, we performed exploratory data analysis on all three predictors and four moments:

We found that the moments are highly correlated:

```{r}
res<-cor(data_train)
res
corrplot(res, tl.col ="black")
```

And that they are linearly correlated:

```{r}
pairs(data_train[4:7], cex = 0.5, pch = 19)
```

```{r}
data_train <- data_train %>%
  mutate(Re_category = case_when(Re == 90 ~ "Low", Re==224 ~ "Medium", Re == 398 ~ "High"))%>%
  mutate(Fr_transformed = invlogit(Fr))
```

We used an inverse-logit function to transform `Fr` due to the infinity values that exist in the data.


```{r}
ctrl <- trainControl(method = "cv", number = 5)

#fit a regression model and use k-fold CV to evaluate performance
model <- train(R_moment_1 ~ St + Re_category + Fr_transformed, data = data_train, method = "lm", trControl = ctrl)

#view summary of k-fold CV               
print(model)
```

```{r}
?train
```


```{r}
lm.fit <- lm(R_moment_1 ~ St + Re_category + Fr_transformed, data = data_train)
summary(lm.fit)
```

## Results

## Conclusion